max_length: 2048
temperature: 1.0
top_k: null  # null = no top_k filtering
top_p: null  # null = no top_p filtering
do_sample: true
num_samples: 2
batch_size: 128  # null = process all prompts at once, or integer for batch size
seed: null  # null = random seed
stop_strings: ['\n\n']  # null = no stop strings, or list of strings to stop generation

